/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import funcoes.Util;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Movimento;
import persistencia.MovimentoDAO;

/**
 *
 * @author Admin
 */
public class JDlgMovimento extends javax.swing.JDialog {
    Movimento movimento;
boolean inclusao;
   MovimentoDAO movimentoDAO;

    /**
     * Creates new form JDlgMovimento
     */
    public JDlgMovimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Movimento");
        //centraliza o frame
        setLocationRelativeTo(null);
        //muda a opção de fechar o formulário com a 
        //aplicação
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Util.habilitar(false, jBtnCancelar, jBtnConfirmar, jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
       String[] colunas = new String[]{"Codigo", "Produto", "Quantidade", "Valor Unitario", "Total"};
        String[][] dados = new String[][]{  
        };
        DefaultTableModel modelo;
        modelo = new DefaultTableModel(dados, colunas);
        jTable1.setModel(modelo);
        setLocationRelativeTo(null);
        movimento = new Movimento();
//        jTxtCodigo.setEnabled(false);
//        jTxtCliente.setEnabled(false);
//        jTxtData.setEnabled(false);
//        jTxtPagamento.setEnabled(false);
    
    }
//    public void habilitar(boolean valor) {
//        jTxtCodigo.setEnabled(valor);
//        jTxtCliente.setEnabled(valor);
//        jTxtData.setEnabled(valor);
//        jTxtPagamento.setEnabled(valor);
//        
//        jBtnIncluir.setEnabled(!valor);
//        jBtnAlterar.setEnabled(!valor);
//        jBtnExcluir.setEnabled(!valor);
//        jBtnConfirmar.setEnabled(valor);
//        jBtnCancelar.setEnabled(valor);
//        jBtnPesqCod.setEnabled(valor);
//    }
//    public void limpar() {
//        jTxtCodigo.setText("");
//        jTxtCliente.setText("");
//        jTxtData.setText("");
//        jTxtPagamento.setText("");
//    }
    public void movimentoTela(Movimento movimento) {
        jTxtCodigo.setText(String.valueOf(movimento.getCodigo()));
        jTxtCliente.setText(movimento.getCliente());
        jTxtData.setText(String.valueOf(movimento.getData()));
        jTxtPagamento.setText(String.valueOf(movimento.getPagamento()));
        
    }

    public Movimento telaMovimento() {
        Movimento movimento = new Movimento();
        
        movimento.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
        movimento.setCliente(jTxtCliente.getText());
        movimento.setData(Integer.parseInt(jTxtData.getText()));
        movimento.setPagamento(Integer.parseInt(jTxtPagamento.getText()));
        
        return movimento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jTxtCliente = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnPesqCod = new javax.swing.JButton();
        jTxtData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtPagamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeincluir.gif"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 253, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeexcluir.gif"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 253, -1, -1));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconalterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 253, -1, -1));

        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 68, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconecancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 253, -1, -1));
        getContentPane().add(jTxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 93, 307, -1));

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeconfirmar.jpg"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 253, -1, -1));

        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 19, -1, -1));

        jBtnPesqCod.setText("...");
        jBtnPesqCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqCodActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesqCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 102, -1, -1));
        getContentPane().add(jTxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 39, 133, -1));

        jLabel4.setText("Codigo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        jLabel3.setText("Pagamento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 82, -1, -1));
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 39, 91, -1));
        getContentPane().add(jTxtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 103, 171, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "Quantidade", "Valor Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 143, 570, 92));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconepesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        inclusao = true;
        Util.habilitar(true, jBtnConfirmar, jBtnCancelar, jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar, jBtnExcluir);
        Util.limpar(jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        //Transferir o foco para o objeto na tela
        jTxtCodigo.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (movimento != null) {
            int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão?", "Exclusao", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                movimentoDAO.delete(movimento);
                Util.limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum grupo está disponível para alteração");
        }

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (movimento != null) {
            inclusao = false;
             Util.habilitar(true, jBtnConfirmar, jBtnCancelar, jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar, jBtnExcluir);
            jTxtCodigo.grabFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum grupo está disponível para alteração");
        }

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
         Util.habilitar(false, jBtnConfirmar, jBtnCancelar, jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar, jBtnExcluir);
         Util.limpar(jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        movimento = null;
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesqCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqCodActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(null, "Entre com o código");
        movimento = (Movimento) movimentoDAO.list(Integer.parseInt(codigo));
        if (movimento == null) {
            JOptionPane.showMessageDialog(null, "código não encontrado.");
        } else {
            movimentoTela(movimento);
        }
    }//GEN-LAST:event_jBtnPesqCodActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        movimento = new Movimento();
        JDlgPesquisarMovimento jDlgPesquisarMovimento = new JDlgPesquisarMovimento(null, true);
        jDlgPesquisarMovimento.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        movimento = telaMovimento();
        Util.habilitar(false);
        Util.limpar(jTxtCodigo, jTxtCliente, jTxtData, jTxtPagamento);
        movimento = null;
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMovimento dialog = new JDlgMovimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesqCod;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCliente;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtData;
    private javax.swing.JTextField jTxtPagamento;
    // End of variables declaration//GEN-END:variables
}
