/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import erros.CampoBrancoException;
import funcoes.Util;
import javax.swing.JOptionPane;
import persistencia.Produto;
import persistencia.ProdutoDAO;

/**
 *
 * @author Admin
 */
public class JDlgProduto extends javax.swing.JDialog {
    Produto produto;
     
   
    boolean inclusao;
    ProdutoDAO produtoDAO;

    /**
     * Creates new form JDlgProduto
     */
    public JDlgProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         produtoDAO = new ProdutoDAO();
        setTitle("Cadastro de Produtos");
        //centraliza o frame
        setLocationRelativeTo(null);
         Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir);
        Util.habilitar(false,  jBtnCancelar, jBtnConfirmar, jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
     Util.limpar(jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);       
//muda a opção de fechar o formulário com a 
        //aplicação
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        jTxtCodigo.setEnabled(false);
//        jTxtNomeproduto.setEnabled(false);
//        jTxtPreco.setEnabled(false);
//        jTxtDescricaoproduto.setEnabled(false);
//        jTxtQtdmin.setEnabled(false);
//        jTxtQtdmax.setEnabled(false);
//        
    }
// public void habilitar(boolean valor) {
//        jTxtCodigo.setEnabled(valor);
//        jTxtNomeproduto.setEnabled(valor);
//        jTxtPreco.setEnabled(valor);
//        jTxtDescricaoproduto.setEnabled(valor);
//        jTxtQtdmin.setEnabled(valor);
//        jTxtQtdmax.setEnabled(valor);
//        jTxtAtivo.setEnabled(valor);
//
//       
//        
//        jBtnIncluir.setEnabled(!valor);
//        jBtnAlterar.setEnabled(!valor);
//        jBtnExcluir.setEnabled(!valor);
//        jBtnConfirmar.setEnabled(valor);
//        jBtnCancelar.setEnabled(valor);
//    }
//    public void limpar() {
//        jTxtCodigo.setText("");
//        jTxtNomeproduto.setText("");
//        jTxtPreco.setText("");
//        jTxtDescricaoproduto.setText("");
//        jTxtQtdmin.setText("");
//        jTxtQtdmax.setText("");
//         jTxtAtivo.setText("");
//     
//    }
    public void produtoTela(Produto produto) {
         
      
        jTxtCodigo.setText(String.valueOf(produto.getCodigo()));
        jTxtNomeproduto.setText(produto.getNomeproduto());
       jTxtPreco.setText(String.valueOf(produto.getPreco()));
        jTxtDescricaoproduto.setText(produto.getDescricaoproduto());
        jTxtQtdmin.setText(String.valueOf(produto.getQtdmin()));
        jTxtQtdmax.setText(String.valueOf(produto.getQtdmax()));
        jChbAtivo.setText(produto.getAtivo());
        
        
    }

    public Produto telaProduto()throws CampoBrancoException {
        Produto produto = new Produto();
        if (jTxtCodigo.getText().equals("")) {
            throw new CampoBrancoException("Código está em branco.");
        } else {
            produto.setCodigo(Integer.parseInt(jTxtCodigo.getText()));
        }
        

        produto.setNomeproduto(jTxtNomeproduto.getText());
        produto.setPreco(Integer.parseInt(jTxtPreco.getText()));
        produto.setDescricaoproduto(jTxtDescricaoproduto.getText());
        produto.setQtdmin(Integer.parseInt(jTxtQtdmin.getText()));
        produto.setQtdmax(Integer.parseInt(jTxtQtdmax.getText()));
        produto.setAtivo(jChbAtivo.getText());
        
        
        
        return produto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnConfirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtDescricaoproduto = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnPesqCod = new javax.swing.JButton();
        jTxtQtdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtQtdmax = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jTxtNomeproduto = new javax.swing.JTextField();
        jBtnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jTxtPreco = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jChbAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeconfirmar.jpg"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 307, -1, -1));

        jLabel3.setText("Descrição do Produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 159, -1, -1));

        jLabel6.setText("Codigo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, -1, -1));
        getContentPane().add(jTxtDescricaoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 179, 216, -1));
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 31, 104, -1));

        jLabel4.setText("Quantidade Minima");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 205, -1, -1));

        jBtnPesqCod.setText("...");
        jBtnPesqCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqCodActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesqCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 256, 80, 40));

        jTxtQtdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQtdminActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtQtdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 225, 91, -1));

        jLabel5.setText("Quantidade Maxima");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 251, -1, -1));
        getContentPane().add(jTxtQtdmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 276, 95, -1));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeincluir.gif"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 307, -1, -1));

        jLabel1.setText("Nome do Produto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 62, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeexcluir.gif"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 307, -1, -1));

        jTxtNomeproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNomeproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 82, 216, -1));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconalterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 307, -1, -1));

        jLabel2.setText("Preço");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 108, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconecancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 307, 120, -1));
        getContentPane().add(jTxtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 128, 99, -1));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconepesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 40));

        jChbAtivo.setText("Ativo");
        jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivoActionPerformed(evt);
            }
        });
        getContentPane().add(jChbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        
        //Pegar valores da tela
        try {
        produto = telaProduto();
} catch (CampoBrancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        System.out.println("Inclusão com sucesso.");
        if (inclusao) {
            produtoDAO.insert(produto);
            //inclusao = false;
        } else {
            produtoDAO.update(produto);
        }
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.habilitar(false,jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        Util.limpar(jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        produto = null;
        //String nomeproduto = jTxtNomeproduto.getText();

        //int codigo = Integer.parseInt(jTxtCodigo.getText());
        //int preco = Integer.parseInt(jTxtPreco.getText());
        //String descricaoproduto = jTxtDescricaoproduto.getText();
        //int qtdmin = Integer.parseInt(jTxtQtdmin.getText());
        //int qtdmax = Integer.parseInt(jTxtQtdmax.getText());
        //String ativo = jTxtAtivo.getText();

        //Gravar valores da tela no objeto usuario
        // produto = new Produto();
        // produto.setCodigo(codigo);
        // produto.setNomeproduto(nomeproduto);
        // produto.setPreco(preco);
        //produto.setDescricaoproduto(descricaoproduto);
        //produto.setQtdmin(qtdmin);
        //produto.setQtdmax(qtdmax);
        //produto.setAtivo(ativo);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesqCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqCodActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(null, "Entre com o código");
        produto = (Produto) produtoDAO.list(Integer.parseInt(codigo));
        if (produto == null) {
            JOptionPane.showMessageDialog(null, "código não encontrado.");
        } else {
            produtoTela(produto);
        }
    }//GEN-LAST:event_jBtnPesqCodActionPerformed

    private void jTxtQtdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQtdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQtdminActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        inclusao = true;
        Util.habilitar(true, jBtnConfirmar, jBtnCancelar,jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar, jBtnExcluir);
        Util.limpar(jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
//Transferir o foco para o objeto na tela

        jTxtCodigo.grabFocus();

    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (produto != null) {
            int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão?", "Excluir", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION){
                produtoDAO.delete(produto);
                Util.limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }

        } else {
            JOptionPane.showMessageDialog(null," Nenhum produto está disponivel para alteração");
        }

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtNomeprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeprodutoActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (produto != null) {
            inclusao = false;
            Util.habilitar(true, jBtnConfirmar, jBtnCancelar,jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar, jBtnExcluir);
            jTxtCodigo.grabFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto está disponível para alteração");
        }
        //        habilitar(true);
        //        jTxtCodigo.grabFocus();
        //
        //        jTxtCodigo.setText(String.valueOf(produto.getCodigo()));
        //        jTxtNomeproduto.setText(produto.getNomeproduto());
        //        jTxtPreco.setText(String.valueOf(produto.getPreco()));
        //        jTxtDescricaoproduto.setText(produto.getDescricaoproduto());
        //        jTxtQtdmin.setText(String.valueOf(produto.getQtdmin()));
        //        jTxtQtdmax.setText(String.valueOf(produto.getQtdmax()));

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jBtnConfirmar, jBtnCancelar,jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar, jBtnExcluir);
          Util.limpar(jTxtCodigo, jTxtNomeproduto, jTxtPreco, jTxtDescricaoproduto, jTxtQtdmin,  jTxtQtdmax, jChbAtivo);
        produto = null;
        //boolean valor = true;
        //jTxtCodigo.setEnabled(false);
        //jTxtNomeproduto.setEnabled(false);
        //jTxtPreco.setEnabled(false);
        //jTxtDescricaoproduto.setEnabled(false);
        //jTxtQtdmin.setEnabled(false);
        //jTxtQtdmax.setEnabled(false);
        //jTxtAtivo.setEnabled(false);

        //jBtnIncluir.setEnabled(valor);
        // jBtnAlterar.setEnabled(valor);
        // jBtnExcluir.setEnabled(valor);
        //jBtnConfirmar.setEnabled(false);
        // jBtnCancelar.setEnabled(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        produto = new Produto();
        JDlgPesquisarProduto jDlgPesquisarProduto = new JDlgPesquisarProduto(null, true);
        jDlgPesquisarProduto.setTelaPai(this);
        jDlgPesquisarProduto.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProduto dialog = new JDlgProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesqCod;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescricaoproduto;
    private javax.swing.JTextField jTxtNomeproduto;
    private javax.swing.JTextField jTxtPreco;
    private javax.swing.JTextField jTxtQtdmax;
    private javax.swing.JTextField jTxtQtdmin;
    // End of variables declaration//GEN-END:variables

    void produto(Produto produto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
