package persistencia;
// Generated 07/07/2016 09:57:56 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private Integer rg;
     private Integer cpf;
     private String apelido;
     private Integer telefone;
     private Integer telefone2;
     private String email;
     private String estado;
     private String cidade;
     private String bairro;
     private String rua;
     private Integer numero;
     private Integer cep;
     private String complemento;
     private String sexo;
     private String profissao;
     private String estadocivil;
     private String nomemae;
     private String nomepai;
     private String alergias;

    public Cliente() {
    }

	
    public Cliente(int codigo) {
        this.codigo = codigo;
    }
    public Cliente(int codigo, String nome, Integer rg, Integer cpf, String apelido, Integer telefone, Integer telefone2, String email, String estado, String cidade, String bairro, String rua, Integer numero, Integer cep, String complemento, String sexo, String profissao, String estadocivil, String nomemae, String nomepai, String alergias) {
       this.codigo = codigo;
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.apelido = apelido;
       this.telefone = telefone;
       this.telefone2 = telefone2;
       this.email = email;
       this.estado = estado;
       this.cidade = cidade;
       this.bairro = bairro;
       this.rua = rua;
       this.numero = numero;
       this.cep = cep;
       this.complemento = complemento;
       this.sexo = sexo;
       this.profissao = profissao;
       this.estadocivil = estadocivil;
       this.nomemae = nomemae;
       this.nomepai = nomepai;
       this.alergias = alergias;
    }

    Cliente(String g2, String grupo_2, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getRg() {
        return this.rg;
    }
    
    public void setRg(Integer rg) {
        this.rg = rg;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public Integer getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }
    public Integer getTelefone2() {
        return this.telefone2;
    }
    
    public void setTelefone2(Integer telefone2) {
        this.telefone2 = telefone2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getCep() {
        return this.cep;
    }
    
    public void setCep(Integer cep) {
        this.cep = cep;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getNomemae() {
        return this.nomemae;
    }
    
    public void setNomemae(String nomemae) {
        this.nomemae = nomemae;
    }
    public String getNomepai() {
        return this.nomepai;
    }
    
    public void setNomepai(String nomepai) {
        this.nomepai = nomepai;
    }
    public String getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(String alergias) {
        this.alergias = alergias;
    }




}


