package persistencia;
// Generated 07/07/2016 09:57:56 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private Integer rg;
     private Integer cpf;
     private String bairro;
     private String rua;
     private Integer numero;
     private String site;
     private Integer cep;
     private String cidade;
     private String estado;
     private Integer telefone;
     private Integer telefone2;
     private String email;

    public Fornecedor() {
    }

	
    public Fornecedor(int codigo) {
        this.codigo = codigo;
    }
    public Fornecedor(int codigo, String nome, Integer rg, Integer cpf, String bairro, String rua, Integer numero, String site, Integer cep, String cidade, String estado, Integer telefone, Integer telefone2, String email) {
       this.codigo = codigo;
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.bairro = bairro;
       this.rua = rua;
       this.numero = numero;
       this.site = site;
       this.cep = cep;
       this.cidade = cidade;
       this.estado = estado;
       this.telefone = telefone;
       this.telefone2 = telefone2;
       this.email = email;
    }

    Fornecedor(String g2, String grupo_2, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getRg() {
        return this.rg;
    }
    
    public void setRg(Integer rg) {
        this.rg = rg;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public Integer getCep() {
        return this.cep;
    }
    
    public void setCep(Integer cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }
    public Integer getTelefone2() {
        return this.telefone2;
    }
    
    public void setTelefone2(Integer telefone2) {
        this.telefone2 = telefone2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


