package persistencia;
// Generated 07/07/2016 09:57:56 by Hibernate Tools 4.3.1



/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int codigo;
     private String nomeproduto;
     private Integer preco;
     private String descricaoproduto;
     private Integer qtdmin;
     private Integer qtdmax;
     private String ativo;

    public Produto() {
    }

	
    public Produto(int codigo) {
        this.codigo = codigo;
    }
    public Produto(int codigo, String nomeproduto, Integer preco, String descricaoproduto, Integer qtdmin, Integer qtdmax, String ativo) {
       this.codigo = codigo;
       this.nomeproduto = nomeproduto;
       this.preco = preco;
       this.descricaoproduto = descricaoproduto;
       this.qtdmin = qtdmin;
       this.qtdmax = qtdmax;
       this.ativo = ativo;
    }

    Produto(String g2, String grupo_2, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNomeproduto() {
        return this.nomeproduto;
    }
    
    public void setNomeproduto(String nomeproduto) {
        this.nomeproduto = nomeproduto;
    }
    public Integer getPreco() {
        return this.preco;
    }
    
    public void setPreco(Integer preco) {
        this.preco = preco;
    }
    public String getDescricaoproduto() {
        return this.descricaoproduto;
    }
    
    public void setDescricaoproduto(String descricaoproduto) {
        this.descricaoproduto = descricaoproduto;
    }
    public Integer getQtdmin() {
        return this.qtdmin;
    }
    
    public void setQtdmin(Integer qtdmin) {
        this.qtdmin = qtdmin;
    }
    public Integer getQtdmax() {
        return this.qtdmax;
    }
    
    public void setQtdmax(Integer qtdmax) {
        this.qtdmax = qtdmax;
    }
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }




}


