package persistencia;
// Generated 07/07/2016 09:57:56 by Hibernate Tools 4.3.1



/**
 * VendaId generated by hbm2java
 */
public class VendaId  implements java.io.Serializable {


     private int codigovenda;
     private int codigoproduto;

    public VendaId() {
    }

    public VendaId(int codigovenda, int codigoproduto) {
       this.codigovenda = codigovenda;
       this.codigoproduto = codigoproduto;
    }
   
    public int getCodigovenda() {
        return this.codigovenda;
    }
    
    public void setCodigovenda(int codigovenda) {
        this.codigovenda = codigovenda;
    }
    public int getCodigoproduto() {
        return this.codigoproduto;
    }
    
    public void setCodigoproduto(int codigoproduto) {
        this.codigoproduto = codigoproduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendaId) ) return false;
		 VendaId castOther = ( VendaId ) other; 
         
		 return (this.getCodigovenda()==castOther.getCodigovenda())
 && (this.getCodigoproduto()==castOther.getCodigoproduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigovenda();
         result = 37 * result + this.getCodigoproduto();
         return result;
   }   


}


