package persistencia;
// Generated 07/07/2016 09:57:56 by Hibernate Tools 4.3.1



/**
 * Vendaproduto generated by hbm2java
 */
public class Vendaproduto  implements java.io.Serializable {


     private int codigo;
     private String cliente;
     private Float data;
     private Float pagamento;
     private Float total;

    public Vendaproduto() {
    }

	
    public Vendaproduto(int codigo) {
        this.codigo = codigo;
    }
    public Vendaproduto(int codigo, String cliente, Float data, Float pagamento, Float total) {
       this.codigo = codigo;
       this.cliente = cliente;
       this.data = data;
       this.pagamento = pagamento;
       this.total = total;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Float getData() {
        return this.data;
    }
    
    public void setData(Float data) {
        this.data = data;
    }
    public Float getPagamento() {
        return this.pagamento;
    }
    
    public void setPagamento(Float pagamento) {
        this.pagamento = pagamento;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


